version '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db_assign1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  volumes:
    postgres_data:   